#!/bin/bash
#PBS -l nodes=1:ppn=1,vmem=20gb,walltime=00:30:00
#PBS -N app-extract-diffusion-by-tissue
#PBS -V

[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

[ ! -f 5tt.nii.gz ] && time singularity exec -e docker://brainlife/mrtrix3:3.0.0 ./convert.sh

time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker:/brainlife/freesurfer:7.3.2 ./move.sh

[ ! -f parc_stats/parc_stats/tissue.csv ] && time singularity exec -e docker://brainlife/dipy:1.4.1 ./build_dataframe.py

if [ ! -f parc-stats/parc-stats/tissues.csv ]; then
	echo "something went wrong. check logs and derivatives"
	exit 1
else
	echo "complete"
	mkdir -p raw
	mv *.nii.gz ./raw/
fi
