#!/bin/bash
#PBS -l nodes=1:ppn=4,vmem=14gb,walltime=00:15:00
#PBS -N app-extract-diffusion-by-tissue
#PBS -V

mask=`jq -r '.mask' config.json`
fa=`jq -r '.fa' config.json`

[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

[ ! -f 5tt.nii.gz ] && time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer-mini:6.0.1 bash -c "export SUBJECTS_DIR=./ && mri_vol2vol --mov ${mask} --targ ${fa} --interp nearest --regheader --o 5tt.nii.gz"

[ ! -f ./output/fa_csf.nii.gz ] && time singularity exec -e docker://brainlife/mrtrix3:3.0.0 ./convert-multiply.sh
